# Generated by Django 2.1 on 2018-10-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181025_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='level',
            field=models.CharField(max_length=20),
        ),
    ]
