# Generated by Django 2.1 on 2018-10-27 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181025_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
